#include <Arduino.h>

#define THERMISTOR1_PIN A0 
#define THERMISTOR1_SERIES_RESISTANCE_KOHM 2.5d
#define THERMISTOR1_NOMINAL_RESISTANCE_KOHM 100.0d
#define THERMISTOR1_NOMINAL_TEMPERATURE 25.0d
#define THERMISTOR1_BCOEFFICIENT 3950.0d

#define THERMISTOR2_PIN A1 
#define THERMISTOR2_SERIES_RESISTANCE_KOHM 10.0d
#define THERMISTOR2_NOMINAL_RESISTANCE_KOHM 100.0d
#define THERMISTOR2_NOMINAL_TEMPERATURE 25.0d
#define THERMISTOR2_BCOEFFICIENT 3950.0d
